receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  hostmetrics:
    root_path: /hostfs
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      disk:
      network:
      load:

processors:
  batch:

exporters:
  influxdb:
    endpoint: http://influxdb:8086
    org: myorg
    bucket: metrics
    token: ${env:INFLUXDB_TOKEN}

service:
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      exporters: [influxdb]
