FROM influxdb:2.7-alpine

# The community image already supports auto-setup via environment variables
# which we have defined in docker-compose.yml.
# We use a custom Dockerfile here to allow for future modifications as requested.
